_BASE_: "base.yaml"
DEBUG: False

MODEL:
  TYPE: 'dtlatefusionsiameseunet'

DATALOADER:
  INPUT_MODE: 's1s2'
  INCLUDE_BUILDING_LABELS: True
  INCLUDE_UNLABELED: True
  USE_TRAIN_AS_UNLABELED: True

CONSISTENCY_TRAINER:
  LOSS_FACTOR_CHANGE: 0.8
  LOSS_FACTOR_SEM: 0.1
  LOSS_FACTOR_CONS: 0.1
  LOSS_TYPE: 'PowerJaccardLoss'