_BASE_: "base.yaml"
DEBUG: False

MODEL:
  TYPE: 'dtmultimodalsiameseunet'

DATALOADER:
  INPUT_MODE: 's1s2'
  INCLUDE_BUILDING_LABELS: True
  INCLUDE_UNLABELED: False
  INCLUDE_UNLABELED_VALIDATION: False