_BASE_: "base.yaml"

TRAINER:
  WARMUP_EPOCHS: 0

MODEL:
  TYPE: 'semicdnet'
  IN_CHANNELS: 2

DATALOADER:
  INPUT_MODE: 's1'
  INCLUDE_UNLABELED: True
  USE_TRAIN_AS_UNLABELED: True

CONSISTENCY_TRAINER:
  LOSS_TYPE: 'PowerJaccardLoss'