_BASE_: "base.yaml"
DEBUG: False

TRAINER:
  BATCH_SIZE: 4

MODEL:
  TYPE: 'whatevernet'

DATALOADER:
  INPUT_MODE: 's1s2'
  INCLUDE_UNLABELED: True
  INCLUDE_UNLABELED_VALIDATION: False

CONSISTENCY_TRAINER:
  LOSS_FACTOR: 0.0
  LOSS_TYPE: 'PowerJaccardLoss'