_BASE_: "base.yaml"
DEBUG: True

TRAINER:
  BATCH_SIZE: 2

MODEL:
  TYPE: 'whatevernet'
  IN_CHANNELS: 3
  OUT_CHANNELS: 1
  TOPOLOGY: [64, 128,]

DATALOADER:
  INPUT_MODE: 's1s2'
  INCLUDE_UNLABELED: True
  INCLUDE_UNLABELED_VALIDATION: False

CONSISTENCY_TRAINER:
  LOSS_FACTOR: 0.9
  LOSS_TYPE: 'PowerJaccardLoss'